### ISSUE TITLE
Merge conflict remnants in various files

### ISSUE THREAD

**Issue by keveleigh** [TobiahZ/FocusAnalytics#1]
Most obviously in https://github.com/TobiahZ/FocusAnalytics/blob/master/ProjectSettings/ProjectVersion.txt,
but also present in various places in https://github.com/TobiahZ/FocusAnalytics/blob/master/ProjectSettings/ProjectSettings.asset#L74.

https://github.com/TobiahZ/FocusAnalytics/search?utf8=%E2%9C%93&q=%3C%3C%3C%3C%3C%3C%3C+HEAD&type=

**Comment by AvinZarlez** [comment]
Crap! Something went wrong there. Thank you for pointing this out! Fixed in latest commit
