### ISSUE TITLE
Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification

### ISSUE THREAD

**Issue by keveleigh** [TobiahZ/FocusAnalytics#2]
Opening this project in Unity (I was using 2017.3) generates several of these errors. I'm not sure if this is a side effect of #1 and maybe Unity regenerating some settings.

![image](https://user-images.githubusercontent.com/3580640/36285702-7ae4972e-1261-11e8-8eef-dd9cb99add63.png)
![image](https://user-images.githubusercontent.com/3580640/36285709-871555d8-1261-11e8-9cad-d57d63e693bd.png)

**Comment by AvinZarlez** [comment]
I believe was a side effect of #1 , should be fixed now. Let me know if further issues. I tested with 2017.3
