### ISSUE TITLE
Duplicate scripts in FocusAnalytics and FocusAnalytics/Scripts

### ISSUE THREAD

**Issue by keveleigh** [TobiahZ/FocusAnalytics#3]
Looks like some scripts were moved without the originals being deleted.

![image](https://user-images.githubusercontent.com/3580640/36285735-ab4eba0c-1261-11e8-89a2-c655fe89d831.png)
![image](https://user-images.githubusercontent.com/3580640/36285744-b3447c56-1261-11e8-9438-bd36f4371f29.png)

Looks like the scenes and prefabs are duplicated as well.

**Comment by AvinZarlez** [comment]
This was likely also part of how there was a bad merge that moved these files, as part of #1. Should be fixed now. Let me know if further issues.
